version: '3'
networks:
  laravel:


services:
    nginx:
      image: nginx:stable-alpine
      container_name: webserver
      ports: 
        - "8088:80"
      volumes:
        - ./:/var/www/html
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
        - mysql
      links:
        - php
      networks:
        - laravel

    mysql:
      image: 'mysql:8.0'
      container_name: mysql
      restart: unless-stopped
      ports:
          - '${FORWARD_DB_PORT:-3306}:3306'
      volumes:
        - ./mysql:/var/lib/mysql

      environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_USER: '${DB_USERNAME}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      networks:
        - laravel

    php:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: php
      volumes:
        - ./:/var/www/html
      ports:
        - "9000:9000"
      networks:
        - laravel
    
    mailhog:
          image: 'mailhog/mailhog:latest'
          ports:
              - 1025:1025
              - 8025:8025
          networks:
              - laravel
