version: '3'
networks:
  laravel:


services:
    nginx:
      image: nginx:stable-alpine
      container_name: nginx
      ports: 
        - "80:80"
        - "443:443"
      volumes:
        - ./:/var/www/html
        - ./nginx/conf.d/:/etc/nginx/conf.d/
      depends_on:
        - php
        - mysql
        - vue
      links:
        - php
      networks:
        - laravel

    mysql:
      image: 'mysql:8.0'
      container_name: database
      restart: unless-stopped
      ports:
          - '${FORWARD_DB_PORT:-3306}:3306'
      volumes:
        - dbdata:/var/lib/mysql

      environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_USER: '${DB_USERNAME}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      networks:
        - laravel

    php:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: app
      working_dir: /var/www/html
      volumes:
        - ./:/var/www/html
      ports:
        - "9000:9000"
      networks:
        - laravel

    # vue:
    #   build: 
    #     context: .
    #     dockerfile: Dockerfile2
    #   ports: 
    #     - 8080:8080
    #   volumes:
    #     - ./:/var/www/html
    
    # mailhog:
    #       image: 'mailhog/mailhog:latest'
    #       ports:
    #           - 1025:1025
    #           - 8025:8025
    #       networks:
    #           - laravel

#Volumes
volumes:
  dbdata:
    driver: local
